# Generated by Django 2.0.2 on 2018-06-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180611_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pPrice',
            field=models.IntegerField(default=0),
        ),
    ]
