# Generated by Django 2.0.2 on 2019-01-29 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pTitle', models.CharField(default='', max_length=200)),
                ('pBrand', models.CharField(default='', max_length=200)),
                ('pModel', models.CharField(default='', max_length=200)),
                ('pOS', models.CharField(default='', max_length=200)),
                ('pProcessor', models.CharField(default='', max_length=200)),
                ('pPrice', models.IntegerField(default=0)),
                ('pCreated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
