# Generated by Django 2.0.2 on 2018-06-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180611_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pModel',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='pOS',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='pPrice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='pProcessor',
            field=models.CharField(max_length=200),
        ),
    ]
