# Generated by Django 2.0.2 on 2018-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180611_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pBrand',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='pModel',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='pOS',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='pPrice',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='pProcessor',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='pTitle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
